---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "dimspace.xyz"
subtitle: "the light at the end of the tunnel is dim"
#logo: "logo.png"
icon: "fas fa-lightbulb" # Optional icon

header: true
footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">Bulma</a>, <a href="https://vuejs.org/">Vue.js</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message

# Optional navbar

links:
  - name: "home server"
    icon: "fas fa-home"
    url: "https://dimspace.xyz#server"
  - name: ""
    icon: ""
    url: ""
    target: '_blank' 
  - name: "lemmy"
    icon: "fas fa-pen"
    url: "https://lemmy.ml/"
    target: '_blank' 
  - name: "mastodon"
    icon: "fas fa-pen-alt"
    url: "https://mastodonapp.uk"
    target: '_blank' 
  - name: "wikipedia"
    icon: "fab fa-wikipedia-w"
    url: "https://wikipedia.com"
    target: '_blank' 
  - name: "theguardian"
    icon: "fas fa-newspaper"
    url: "https://www.theguardian.com/uk"
    target: '_blank' 
  - name: "yougov"
    icon: "fas fa-poll-h"
    url: "https://yougov.co.uk"
    target: '_blank' 

# Services

services:
  - name: "Social"
    icon: "fas fa-thumbs-up"
    items:
      - name: "Mastodon"
        logo: "assets/tools/mastodon.png"
        subtitle: "my mastodon profile"
        tag: "not owned by elon"
        url: "https://mastodonapp.uk/@dimspace"
        target: '_blank' 
      - name: "Twitter"
        logo: "assets/tools/twitter.png"
        subtitle: "follow me on twitter"
        tag: "tweet"
        url: "https://twitter.com/dimspace"
        target: '_blank' 
      - name: "Lemmy"
        logo: "assets/tools/lemmy.png"
        subtitle: "the decentralised 'reddit'"
        tag: "post"
        url: "https://lemmy.ml/u/dimspace"
        target: '_blank' 
      - name: "Reddit"
        logo: "assets/tools/reddit.png"
        subtitle: "my reddit profile"
        tag: "post"
        url: "https://www.reddit.com/user/dimspace/"
        target: '_blank' 
      - name: "Facebook"
        logo: "assets/tools/facebook.png"
        subtitle: "i don't use this much"
        tag: "post"
        url: "https://facebook.com/dimspace"
        target: '_blank' 
      - name: "Instagram"
        logo: "assets/tools/instagram.png"
        subtitle: "i use this even less"
        tag: "post"
        url: "https://instagram.com/dimspace"
        target: '_blank' 
      - name: "youtube"
        logo: "assets/tools/youtube.png"
        subtitle: "um"
        tag: "play"
        url: "#"
        target: '_blank' 
  - name: "My Writing"
    icon: "fas fa-pen-alt"
    items:
      - name: "Blog"
        logo: "assets/tools/wordpress.png"
        #icon: "fab fa-wordpress"
        subtitle: "my blog"
        tag: "blog"
        url: "https://blog.dimspace.xyz"
        target: '_blank' 
      - name: "Bodylock MMA"
        logo: "assets/tools/tbl.png"
        subtitle: "my work on the bodylock mma"
        tag: "mma"
        url: "https://thebodylockmma.com/author/davemarsdin/"
        target: '_blank' 
      - name: "Cyclismas"
        #logo: "assets/tools/tbl.png"
        icon: "fas fa-bicycle"
        subtitle: "old cycling ramblings"
        tag: "cycling"
        url: "http://www.cyclismas.com/biscuits/author/dimspace/"
        target: '_blank' 
  - name: "Sound & Vision"
    icon: "fas fa-play"
    items:
      - name: "Last.fm"
        logo: "assets/tools/lastfm.png"
        subtitle: "what i listen to"
        tag: "music"
        url: "https://last.fm/user/dimspace"
        target: '_blank' 
      - name: "Trakt.tv"
        logo: "assets/tools/trakt.png"
        subtitle: "what i watch"
        url: "https://trakt.tv/users/dimspace"
        target: '_blank' 
        tag: "tv"
      - name: "Musicbrainz"
        logo: "assets/tools/musicbrainz.png"
        subtitle: "my complete music collection"
        tag: "music"
        url: "https://musicbrainz.org/collection/7a1289c9-2e2a-4c81-80ff-ba14f044357d"
        target: '_blank' 
      - name: "The Audio Database"
        logo: "assets/tools/bars.png"
        subtitle: "my audiodb edits"
        tag: "music"
        url: "https://www.theaudiodb.com/user/dimspace"
        target: '_blank' 
  - name: "Gaming"
    icon: "fas fa-ghost"
    items:
      - name: "PSN Profiles"
        logo: "assets/tools/psnprofiles.png"
        subtitle: "my trophy history"
        tag: "playstation"
        url: "https://psnprofiles.com/daveM12DIM"
        target: '_blank'
      - name: "Twitch"
        logo: "assets/tools/twitch.png"
        subtitle: "my twitch"
        tag: "stream"
        url: "https://www.twitch.tv/davem12dim"
        target: '_blank'
      - name: "Price Charting"
        logo: "assets/tools/pricecharting.png"
        subtitle: "my video game collection"
        tag: "games"
        url: "https://www.pricecharting.com/offers?seller=pzuk6hvbd6kh2diqvnaj7g2nlu&status=collection"
        target: '_blank'
  - name: "Geek Stuff"
    icon: "fas fa-code-branch"
    items:
      - name: "Github"
        logo: "assets/tools/github.png"
        subtitle: "my git"
        tag: "git"
        url: "http://github.com/dm2912"
        target: '_blank' 
      - name: "Gitea"
        logo: "assets/tools/gitea.png"
        subtitle: "self hosted git"
        tag: "git"
        tagstyle: "is-success"
        url: "https://git.dimspace.xyz"
        target: '_blank'
      - name: "Userstyles"
        logo: "assets/tools/userstyles.png"
        subtitle: "my custom styles on userstyles"
        url: "https://userstyles.org/users/304746"
        target: '_blank' 
        tag: "css"
      - name: "Wikipedia"
        logo: "assets/tools/wikipedia.png"
        subtitle: "my wiki edits"
        tag: "wiki"
        url: "https://en.wikipedia.org/wiki/User_talk:Dimspace"
        target: '_blank' 
  - name: "Anti doping"
    icon: "fas fa-syringe"
    items:
      - name: "UFC Testing"
        logo: "assets/tools/usada.png"
        subtitle: "ufc/usada test stats spreadsheet"
        tag: "usada"
        url: "https://short.dimspace.xyz/ufcusada"
        target: '_blank' 
      - name: "UFC Test Records"
        logo: "assets/tools/ufc.png"
        subtitle: "various ufc athlete test results"
        url: "https://cloud.dimspace.xyz/s/8inB9xMtRXL7dPd"
        target: '_blank' 
        tag: "css"
      - name: "Operation Puerto"
        logo: "assets/tools/spain.png"
        subtitle: "various Operation Puerto evidence"
        tag: "fuentes"
        url: "hhttps://short.dimspace.xyz/puerto"
        target: '_blank' 
      - name: "Lance Armstrong"
        logo: "assets/tools/texas.png"
        subtitle: "a bunch of Armstrong related stuff"
        tag: "big tex"
        url: "https://short.dimspace.xyz/lance"
        target: '_blank' 
      - name: "Blog"
        logo: "assets/tools/wordpress.png"
        #icon: "fab fa-wordpress"
        subtitle: "my blog"
        tag: "blog"
        url: "https://blog.dimspace.xyz/"
        target: '_blank' 
      - name: "Bodylock MMA"
        logo: "assets/tools/tbl.png"
        subtitle: "my work on the bodylock mma"
        tag: "mma"
        url: "https://thebodylockmma.com/author/davemarsdin/"
        target: '_blank'
